# Generated by Django 5.2.4 on 2025-07-16 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('due', models.DateField(default=django.utils.timezone.now)),
                ('category', models.TextField(choices=[('D', 'Daily'), ('W', 'Montly'), ('M', 'Weekly')], max_length=1)),
                ('completed', models.BooleanField(default=False)),
                ('now', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
